//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.08.04 at 03:12:45 AM EET 
//


package com.ericsson.java.prototype.soap.services;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.ericsson.java.prototype.soap.services package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.ericsson.java.prototype.soap.services
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GetSubscriberByIdResponse }
     * 
     */
    public GetSubscriberByIdResponse createGetSubscriberByIdResponse() {
        return new GetSubscriberByIdResponse();
    }

    /**
     * Create an instance of {@link Subscribers }
     * 
     */
    public Subscribers createSubscribers() {
        return new Subscribers();
    }

    /**
     * Create an instance of {@link GetAllSubscribersRequest }
     * 
     */
    public GetAllSubscribersRequest createGetAllSubscribersRequest() {
        return new GetAllSubscribersRequest();
    }

    /**
     * Create an instance of {@link GetAllSubscribersResponse }
     * 
     */
    public GetAllSubscribersResponse createGetAllSubscribersResponse() {
        return new GetAllSubscribersResponse();
    }

    /**
     * Create an instance of {@link GetSubscriberByIdRequest }
     * 
     */
    public GetSubscriberByIdRequest createGetSubscriberByIdRequest() {
        return new GetSubscriberByIdRequest();
    }

}
