//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.08.06 at 02:11:48 AM EET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.ericsson.com/java/prototype/soap/services", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.ericsson.java.prototype.soap.services;
